### ISSUE TITLE
Fail to fetch files on Ubunti Xenial - could you please recommend workaround?

### ISSUE THREAD

**Issue by solt6626** [berlius/DeepLearningDockerfile#1]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/n/nspr/libnspr4_4.10.10-0ubuntu0.14.04.1_amd64.deb  404  Not Found [IP: 91.189.88.152 80]

E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/n/nss/libnss3-nssdb_3.21-0ubuntu0.14.04.2_all.deb  404  Not Found [IP: 91.189.88.152 80]

E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/n/nss/libnss3_3.21-0ubuntu0.14.04.2_amd64.deb  404  Not Found [IP: 91.189.88.152 80]

E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/t/tzdata/tzdata-java_2016d-0ubuntu0.14.04_all.deb  404  Not Found [IP: 91.189.88.152 80]

E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/o/openjdk-7/openjdk-7-jre-headless_7u101-2.6.6-0ubuntu0.14.04.1_amd64.deb  404  Not Found [IP: 91.189.88.152 80]

E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/o/openjdk-7/openjdk-7-jre_7u101-2.6.6-0ubuntu0.14.04.1_amd64.deb  404  Not Found [IP: 91.189.88.152 80]

E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/universe/x/xerces-c/libxerces-c3.1_3.1.1-5.1+deb8u2build0.14.04.1_amd64.deb  404  Not Found [IP: 91.189.88.152 80]

E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/o/openjdk-7/openjdk-7-jdk_7u101-2.6.6-0ubuntu0.14.04.1_amd64.deb  404  Not Found [IP: 91.189.88.152 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
The command '/bin/sh -c apt-get install -y libboost-all-dev         libpython2.7         openjdk-7-jdk         lua5.1         libxerces-c3.1         liblua5.1-0-dev         libav-tools python-tk         gnome-terminal' returned a non-zero code: 100

**Comment by berlius** [comment]
yes Dockerfile was made only a few weeks ago and is already outdated !!

I just update because Microsoft malmo now runs on Java 8 and upload the container on dockerhub

you can download the container:

docker pull berlius/microsoft-malmo:gpu

or compile locally by following the updated  "readme.md"

thanks

**Comment by berlius** [comment]
the problem seems solved

closing
