### ISSUE TITLE
build fails at The command '/bin/sh -c apt-get install -y openjdk-8-jdk' returned a non-zero code: 100

### ISSUE THREAD

**Issue by solt6626** [berlius/DeepLearningDockerfile#2]
**_@**_-Inspiron-***:~/repos/DeepLearningDockerfile/Microsoft-malmo$ sudo docker build -t berlius/microsoft-malmo:gpu -f Dockerfile .
[sudo] solio jelszava: 
Sending build context to Docker daemon 11.78 kB
Step 1 : FROM berlius/artificial-intelligence-gpu
 ---> 1f949e1a7ddf
Step 2 : MAINTAINER berlius berlius52@yahoo.com
 ---> Using cache
 ---> 8e2e25050644
Step 3 : RUN add-apt-repository ppa:openjdk-r/ppa
 ---> Using cache
 ---> 9ad42549bcc7
Step 4 : RUN apt-get update
 ---> Using cache
 ---> 11f0c26e1102
Step 5 : RUN apt-get install -y openjdk-8-jdk
 ---> Running in 9b00404d715d
Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  openjdk-8-jdk-headless openjdk-8-jre openjdk-8-jre-headless
Suggested packages:
  openjdk-8-demo openjdk-8-source visualvm icedtea-8-plugin
  openjdk-8-jre-jamvm libnss-mdns fonts-ipafont-gothic fonts-ipafont-mincho
  ttf-wqy-microhei ttf-wqy-zenhei ttf-indic-fonts-core ttf-telugu-fonts
  ttf-oriya-fonts ttf-kannada-fonts ttf-bengali-fonts
The following NEW packages will be installed:
  openjdk-8-jdk openjdk-8-jdk-headless openjdk-8-jre openjdk-8-jre-headless
0 upgraded, 4 newly installed, 0 to remove and 17 not upgraded.
Need to get 35.4 MB of archives.
After this operation, 139 MB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  openjdk-8-jre-headless openjdk-8-jre openjdk-8-jdk-headless openjdk-8-jdk
E: There are problems and -y was used without --force-yes
The command '/bin/sh -c apt-get install -y openjdk-8-jdk' returned a non-zero code: 100

**Comment by solt6626** [comment]
By the way, thank you very much for putting together this project. Hope I manage to build it on my machine. I am a beginner in Artificial Intelligence, and would like to learn it by playing my favorite program, Minecraft.

**Comment by berlius** [comment]
This is a very good idea to take an interest in AI. welcome !

There is still much work to train a good agent in MINECRAFT

GPG signature of the server "PPA" has not been registered

if you type in a terminal:

apt-key list

the answer is a list. Is there :

## /etc/apt/trusted.gpg.d/openjdk-r_ubuntu_ppa.gpg

pub 1024R / 86F44E2A 2010-04-12
uid Launchpad OpenJDK builds (all archs)

have you "gpg" installed on your system? if not

sudo apt-get install gnupg

there is also a GUI to fix problems GPG

sudo add-apt-repository ppa: webupd8team / y-ppa-manager
sudo apt-get update
sudo apt-get install y-ppa-manager

Open Y PPA Manager from dash
Double click on advanced
Click "Try to import all missing GPG keys"

you find attached the "install.log"
[install.txt](https://github.com/berlius/DeepLearningDockerfile/files/440365/install.txt)

**Comment by solt6626** [comment]
Thank you Berlius.
After following your instrcutions apt.key list shows me this entry among others:

## /etc/apt/trusted.gpg.d/openjdk-r_ubuntu_ppa.gpg

pub   1024R/86F44E2A 2010-04-12
uid                  Launchpad OpenJDK builds (all archs)

but when I try to build the image I still get the same error message:
Step 5 : RUN apt-get install -y openjdk-8-jdk
 ---> Running in 00f3058c20f4
Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  openjdk-8-jdk-headless openjdk-8-jre openjdk-8-jre-headless
Suggested packages:
  openjdk-8-demo openjdk-8-source visualvm icedtea-8-plugin
  openjdk-8-jre-jamvm libnss-mdns fonts-ipafont-gothic fonts-ipafont-mincho
  ttf-wqy-microhei ttf-wqy-zenhei ttf-indic-fonts-core ttf-telugu-fonts
  ttf-oriya-fonts ttf-kannada-fonts ttf-bengali-fonts
The following NEW packages will be installed:
  openjdk-8-jdk openjdk-8-jdk-headless openjdk-8-jre openjdk-8-jre-headless
0 upgraded, 4 newly installed, 0 to remove and 17 not upgraded.
Need to get 35.4 MB of archives.
After this operation, 139 MB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  openjdk-8-jre-headless openjdk-8-jre openjdk-8-jdk-headless openjdk-8-jdk
E: There are problems and -y was used without --force-yes
The command '/bin/sh -c apt-get install -y openjdk-8-jdk' returned a non-zero code: 100

If I try to pull the image from docker hub, and issue the following command, i get a different error. please advise.

solio@solio-Inspiron-7559:~/repos/DeepLearningDockerfile/Microsoft-malmo$ xhost + ; sudo nvidia-docker run -it -p 8888:8888 -p 6006:6006 -p 8000:8000 -v `pwd`:/root/sharedfolder -v /mnt/sda4:/root/sda4 --privileged --device=/dev/snd:/dev/snd -v /tmp/.X11-unix:/tmp/.X11-unix:ro -e DISPLAY=unix$DISPLAY berlius/microsoft-malmo:gpu lxterminal
access control disabled, clients can connect from any host
[sudo] solio jelszava: 
Gtk-Message: Failed to load module "canberra-gtk-module"

**Comment by berlius** [comment]
well the server is registered but it seems that you still do not have GPG installed on your system. Try to install it following the two methods of my previous message.

Gtk-Message: Failed to load the module "canberra-gtk module

this is not an error message, it is just an information
You should see "LXTerminal" opened in a corner of your screen
It may be small and inconspicuous
You can manually expand

**Comment by berlius** [comment]
the problem seems solved

closing
